/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9tBqbBlrNoj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex items-start justify-center space-x-4">
      <Card>
        <CardHeader>
          <CardTitle>Background</CardTitle>
          <CardDescription>Change the background color</CardDescription>
        </CardHeader>
        <CardContent className="flex items-center justify-center p-8">
          <input className="rounded-md border border-gray-200 w-10 h-10" type="color" />
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Accent</CardTitle>
          <CardDescription>Change the accent color</CardDescription>
        </CardHeader>
        <CardContent className="flex items-center justify-center p-8">
          <input className="rounded-md border border-gray-200 w-10 h-10" type="color" />
        </CardContent>
      </Card>
    </div>
  )
}
