/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cs7K1QFWmPH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function DashboardExample() {
  return (
    <div key="1" className="flex min-h-screen">
      <div className="hidden w-64 flex-col border-r bg-gray-100 p-6 dark:border-gray-800 dark:bg-gray-900 lg:flex">
        <Link className="flex items-center gap-2 font-semibold text-[#0077b6]" href="#">
          <MountainIcon className="h-6 w-6" />
          <span>Bordly</span>
        </Link>
        <nav className="mt-8 flex flex-col space-y-4">
          <Link
            className="flex items-center gap-2 rounded-md px-3 py-2 text-gray-500 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
            href="#"
          >
            <TypeIcon className="h-5 w-5" />
            Typography
          </Link>
          <Link
            className="flex items-center gap-2 rounded-md px-3 py-2 text-gray-500 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
            href="#"
          >
            <PaletteIcon className="h-5 w-5" />
            Color Palette
          </Link>
          <Link
            className="flex items-center gap-2 rounded-md px-3 py-2 text-gray-500 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
            href="#"
          >
            <ImageIcon className="h-5 w-5" />
            Icons
          </Link>
          <Link
            className="flex items-center gap-2 rounded-md px-3 py-2 text-gray-500 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
            href="#"
          >
            <ComponentIcon className="h-5 w-5" />
            UI Components
          </Link>
        </nav>
      </div>
      <div className="flex-1 p-6">
        <div className="mb-8 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <MountainIcon className="h-6 w-6 text-[#0077b6]" />
            <h1 className="text-2xl font-bold text-[#0077b6]">Bordly</h1>
          </div>
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  className="border-[#0077b6] text-[#0077b6] hover:bg-[#0077b6] hover:text-white dark:border-gray-400 dark:text-gray-400 dark:hover:bg-gray-400 dark:hover:text-gray-900"
                  size="sm"
                  variant="outline"
                >
                  <SettingsIcon className="h-4 w-4 mr-2" />
                  Settings
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem>General</DropdownMenuItem>
                <DropdownMenuItem>Branding</DropdownMenuItem>
                <DropdownMenuItem>Accessibility</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Export</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Button
              className="border-[#0077b6] text-[#0077b6] hover:bg-[#0077b6] hover:text-white dark:border-gray-400 dark:text-gray-400 dark:hover:bg-gray-400 dark:hover:text-gray-900"
              size="sm"
              variant="outline"
            >
              <DownloadIcon className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>
        </div>
        <Tabs className="w-full" defaultValue="typography">
          <TabsList className="mb-6 flex w-full border-b">
            <TabsTrigger value="typography">Typography</TabsTrigger>
            <TabsTrigger value="color-palette">Color Palette</TabsTrigger>
            <TabsTrigger value="icons">Icons</TabsTrigger>
            <TabsTrigger value="components">UI Components</TabsTrigger>
          </TabsList>
          <TabsContent value="typography">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Headings</CardTitle>
                  <CardDescription>The primary headings used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div>
                      <h1 className="text-4xl font-bold">Heading 1</h1>
                      <p className="text-gray-500 dark:text-gray-400">Used for page titles and hero sections.</p>
                    </div>
                    <div>
                      <h2 className="text-3xl font-bold">Heading 2</h2>
                      <p className="text-gray-500 dark:text-gray-400">
                        Used for section titles and major content blocks.
                      </p>
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold">Heading 3</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Used for subsection titles and feature descriptions.
                      </p>
                    </div>
                    <div>
                      <h4 className="text-xl font-bold">Heading 4</h4>
                      <p className="text-gray-500 dark:text-gray-400">
                        Used for card titles and other medium-sized headings.
                      </p>
                    </div>
                    <div>
                      <h5 className="text-lg font-bold">Heading 5</h5>
                      <p className="text-gray-500 dark:text-gray-400">Used for small headings and labels.</p>
                    </div>
                    <div>
                      <h6 className="text-base font-bold">Heading 6</h6>
                      <p className="text-gray-500 dark:text-gray-400">Used for tiny headings and captions.</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Body Text</CardTitle>
                  <CardDescription>The primary body text styles used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div>
                      <p className="text-base font-normal">
                        This is the default body text. It is used for the majority of the content on the site.
                      </p>
                    </div>
                    <div>
                      <p className="text-sm font-normal">
                        This is a smaller body text size, used for captions, labels, and other secondary content.
                      </p>
                    </div>
                    <div>
                      <p className="text-xs font-normal">
                        This is the smallest body text size, used for very minor details and legal copy.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Font Families</CardTitle>
                  <CardDescription>The primary font families used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div>
                      <h4 className="text-lg font-bold">Heading Font</h4>
                      <p className="font-heading text-2xl font-bold">Roboto Slab</p>
                    </div>
                    <div>
                      <h4 className="text-lg font-bold">Body Font</h4>
                      <p className="font-body text-2xl">Inter</p>
                    </div>
                    <div>
                      <h4 className="text-lg font-bold">Monospace Font</h4>
                      <p className="font-mono text-2xl">Fira Code</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="color-palette">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Background Colors</CardTitle>
                  <CardDescription>The background colors used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-white" />
                      <p className="text-sm font-medium">White</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-gray-100" />
                      <p className="text-sm font-medium">Gray 100</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-gray-900" />
                      <p className="text-sm font-medium">Gray 900</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Copy Colors</CardTitle>
                  <CardDescription>The foreground colors used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-[#808080]" />
                      <p className="text-sm font-medium">Gray 500</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-[#4b5563]" />
                      <p className="text-sm font-medium">Gray 700</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-[#111827]" />
                      <p className="text-sm font-medium">Gray 900</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Primary Colors</CardTitle>
                  <CardDescription>The primary colors used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-[#0077b6]" />
                      <p className="text-sm font-medium">Primary</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-white text-[#0077b6]" />
                      <p className="text-sm font-medium">Primary Foreground</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Accent Colors</CardTitle>
                  <CardDescription>The accent colors used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-[#ff5722]" />
                      <p className="text-sm font-medium">Accent</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="h-16 w-16 rounded-full bg-white text-[#ff5722]" />
                      <p className="text-sm font-medium">Accent Foreground</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="icons">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>System Icons</CardTitle>
                  <CardDescription>The primary system icons used throughout the design system.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-4 gap-4">
                    <div className="flex flex-col items-center gap-2">
                      <HomeIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Home</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <SearchIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Search</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <BellIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Notifications</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <SettingsIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Settings</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <UserIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Profile</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <MenuIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Menu</p>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                      <CalendarIcon className="h-8 w-8 text-[#0077b6]" />
                      <p className="text-sm font-medium">Calendar</p>
                    </div>
                    <div className="flex flex-col items-center gap-2" />
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function ComponentIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
      <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
      <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
      <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
    </svg>
  )
}


function DownloadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PaletteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="13.5" cy="6.5" r=".5" />
      <circle cx="17.5" cy="10.5" r=".5" />
      <circle cx="8.5" cy="7.5" r=".5" />
      <circle cx="6.5" cy="12.5" r=".5" />
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function TypeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
